# Exercise 3: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [6]:
#3.2: create a random 10x10 array named A
A=np.random.randn(10,10)
print(A)
np.shape(A)

[[-0.7525134  -0.71307197 -0.40492135 -0.82881466 -1.00041233  0.1908945
  -0.72037979  0.19352087 -0.74383652 -0.50004742]
 [-0.13954726  1.14386284 -0.24521378 -0.42694944 -0.84047095 -0.07233189
  -0.41401667 -0.7865576   2.14837744 -0.42381782]
 [ 1.18326564  0.1990713  -2.12236767 -0.16950161 -1.61631698  1.24595948
   1.26482065  0.02112605  0.02374395  0.54271676]
 [ 1.17262315 -0.59551337  0.32084333  1.07543513 -0.25756756 -0.09070049
   0.00252358  0.29306886  0.78861925 -1.2178918 ]
 [-0.40137725  0.36883886  2.24806394  0.81502715  0.01473427  1.21219901
  -0.3194371   0.05574924 -0.16301137  0.99460023]
 [ 1.40644202  0.40186216  0.94690267  0.76173264  0.2848186  -1.23531478
   0.2277025   0.48183792  0.70304366 -0.30361021]
 [-1.5283579   0.98729276  0.85668585  1.29970336 -0.53382839 -0.17800277
  -0.64305587 -1.0242999  -0.41987722 -1.93098567]
 [ 1.763637   -0.83752922  1.62338244  0.90940518 -1.73298998 -0.49451985
   0.66509952 -0.59841282  0.52396398 -1.55306837]
 

(10, 10)

In [36]:
#3.3: return only the odd rows of A
#print(A[[1,3,5,7,9],]) #je nachdem,weil man mit 0 anfängt zu zählen 
print(A[[0,2,4,6,8],[0]]) #Werte det 1.Spalte der Zeile 1,3,5,7,9 werden ausgegeben 

[-0.7525134   0.29581641 -0.40137725 -1.5283579   0.42136501]


In [21]:
#3.4: perform a matrix multiplication of A with it's transposed
trans_A=np.transpose(A)
#print(trans_A)
A*trans_A

array([[ 5.66276414e-01,  9.95072401e-02, -4.79129525e-01,
        -9.71887257e-01,  4.01542747e-01,  2.68482053e-01,
         1.10099815e+00,  3.41300561e-01, -3.13426682e-01,
        -4.61737991e-01],
       [ 9.95072401e-02,  1.30842219e+00, -4.88150280e-02,
         2.54254103e-01, -3.09998345e-01, -2.90674477e-02,
        -4.08755657e-01,  6.58764975e-01,  3.20733588e+00,
         6.36648657e-02],
       [-4.79129525e-01, -4.88150280e-02,  4.50444451e+00,
        -5.43834610e-02, -3.63358391e+00,  1.17980237e+00,
         1.08355395e+00,  3.42956654e-02, -1.39911462e-02,
         2.87765155e-01],
       [-9.71887257e-01,  2.54254103e-01, -5.43834610e-02,
         1.15656072e+00, -2.09924557e-01, -6.90895208e-02,
         3.27990033e-03,  2.66518340e-01, -7.88852881e-01,
        -2.06296776e+00],
       [ 4.01542747e-01, -3.09998345e-01, -3.63358391e+00,
        -2.09924557e-01,  2.17098767e-04,  3.45256823e-01,
         1.70524590e-01, -9.66128823e-02,  1.44557777e-01,
        -1.

In [24]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)

array([[ 6.37021943e-01, -4.83178871e+01, -3.29457631e+01,
         4.64174962e+01,  1.64942994e+01, -5.45372236e+01,
        -2.23300868e+01, -2.69941023e+01,  7.52973444e+01,
         4.80466767e+01],
       [ 1.31277214e-01, -9.78544121e+00, -6.45616804e+00,
         9.14354806e+00,  3.44679709e+00, -1.05923708e+01,
        -4.24312365e+00, -5.60341478e+00,  1.53654035e+01,
         9.58928881e+00],
       [-1.65388808e-01,  9.91252541e+00,  6.68628283e+00,
        -9.73708228e+00, -3.20781992e+00,  1.13399224e+01,
         4.55572402e+00,  5.82951935e+00, -1.54625693e+01,
        -1.00438721e+01],
       [-2.24764881e-02,  4.75892060e-02,  1.32248191e-01,
         2.74428506e-01,  6.21042913e-02,  8.65917848e-02,
         1.63468468e-01, -2.64437577e-01, -2.25850557e-01,
         2.44705037e-01],
       [-3.40689413e-01, -1.08830662e+01, -7.55273538e+00,
         1.04910440e+01,  3.54312896e+00, -1.24464306e+01,
        -4.98029881e+00, -6.04203757e+00,  1.68090028e+01,
         1.

In [33]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
searchpara = (A > 0.5)
indices=np.where(searchpara)
print(indices)
A_2=A[indices]/2
#print(A_2)
A[indices]=A_2
print(A)
#print(A[0,1]) Zeile 0 Spalte1

(array([], dtype=int64), array([], dtype=int64))
[[-0.7525134  -0.71307197 -0.40492135 -0.82881466 -1.00041233  0.1908945
  -0.72037979  0.19352087 -0.74383652 -0.50004742]
 [-0.13954726  0.28596571 -0.24521378 -0.42694944 -0.84047095 -0.07233189
  -0.41401667 -0.7865576   0.26854718 -0.42381782]
 [ 0.29581641  0.1990713  -2.12236767 -0.16950161 -1.61631698  0.31148987
   0.31620516  0.02112605  0.02374395  0.27135838]
 [ 0.29315579 -0.59551337  0.32084333  0.26885878 -0.25756756 -0.09070049
   0.00252358  0.29306886  0.39430963 -1.2178918 ]
 [-0.40137725  0.36883886  0.28100799  0.40751357  0.01473427  0.30304975
  -0.3194371   0.05574924 -0.16301137  0.49730011]
 [ 0.35161051  0.40186216  0.47345134  0.38086632  0.2848186  -1.23531478
   0.2277025   0.48183792  0.35152183 -0.30361021]
 [-1.5283579   0.49364638  0.42834292  0.32492584 -0.53382839 -0.17800277
  -0.64305587 -1.0242999  -0.41987722 -1.93098567]
 [ 0.44090925 -0.83752922  0.40584561  0.45470259 -1.73298998 -0.49451985
   